### ISSUE TITLE
few issues in 2.91

### ISSUE THREAD

**Issue by 3diuk** [nutti/Screencast-Keys#32]
following problems

Letters appear as solid cubes instead of text
![image](https://user-images.githubusercontent.com/22356973/95808818-392a4080-0d05-11eb-834d-95cc6b8a8463.png)

Only works in the initial workspace, even though it still shows as enabled in the n panel.

updater gives following error:

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\blender\\shared_files_between_versions\\scripts\\addons\\screencast_key/addon_updator_workspace

**Comment by nutti** [comment]
@3diuk 

Thanks for early feedback of this add-on.
I tried the add-on in Blender 2.91, but I could not reproduce this error.
In my environment it seems work correctly.

> updater gives following error:

But I reproduce this error.
I will fix this for now.

**Comment by nutti** [comment]
> updater gives following error:

This bug is now fixed.

> Letters appear as solid cubes instead of text

Could you check your environment for this?
I think it does not seem the issue of this add-on.

**Comment by 3diuk** [comment]
Thanks, the updater is now working.

Two issues now remain:

1. The text still diaplays as solid cubes.  Did you change the font recently perhaps?
2. doesn't work when you change workspaces even though still shows enabled in the new workspace

**Comment by 3diuk** [comment]
scrap point 2. I've just found that setting the origin to 'window' resolves that.  So just the font problem.

**Comment by 3diuk** [comment]
I've just tried downgrading blender to a build from 7th october, and it seems to be ok.  Perhaps an api change has broken it:

https://wiki.blender.org/wiki/Reference/Release_Notes/2.91/Python_API

**Comment by 3diuk** [comment]
problem gone in todays build.

**Comment by nutti** [comment]
I'm glad to solve your problem.
